pipelines:
  ### Sub-Pipelines ###
  # Trimming and FastQC
  qc:
    stages:
      - qc_fastqc
      - trim_bbmapAQ10L70
      - qc_fastqc

  # Keep *only* reads matching last *.fasta.gz (from ref)
  enrich:
    stages:
      - map_bbmapS:
          hide: true
      - extract_readsG12

  # Remove reads matching last bowtie2 and hisat2 indicies (from ref)
  deplete:
    stages:
      - map_hisat2:
          hide: true
      - extract_readsf12:
          hide: true
      - map_bowtie2:
          hide: true
      - extract_readsf12

  # Assemble (by sample) using Spades Single Cell mode and remove short contigs
  assemble_single:
    stages:
      - group_sample
      - assemble_spadesSc:
          hide: true
      - format_bbmapL200

  # Assemble (by sample) using Spades Metagenomic mode and remove short contigs
  # (removes low entropy reads prior to assembly)
  assemble_meta:
    stages:
      - dust_bbmapE60:
          hide: true
      - group_sample
      - assemble_spadesMeta:
          hide: true
      - format_bbmapL200

  # Compute coverage and sorted bam file using bowtie2
  coverage:
    stages:
      - index_bowtie2:
          hide: true
      - map_bowtie2S:
          hide: true
      - sort_bam:
          hide: true
      - markdup_sambambaRM
      - coverage_samtools
      - basecov_bedtools

  # Remove human contigs and create classified bins using BLAST
  blastbin:
    stages:
      - ref_hg38:
          hide: true
      - annotate_blastE2MegaBest:
          hide: true
      - blastfilter_vpU200:
          hide: true
      - ref_NT:
          hide: true
      - annotate_blastE10Best:
          hide: true
      - ref_NcbiTaxonomy:
          hide: true
      - group_sample:
          hide: true
      - blastbin_vp

  scaffold:
    stages:
      - scaffold_vp
      - coverage:
          hide: true
      - group_sample
      - polish_pilonSIL:
          hide: true
      - coverage
      - group_ALL
      - bin_vpSpecies

  summarize:
    stages:
      - ref_VHDB
      - group_ALL
      - summarize_vp

  # Re-Assemble created bins
  reassemble:
    stages:
      - enrich:
          hide: true
      - group_sample
      - group_BIN
      - assemble_spadesSc:
          hide: true
      - group_sample
      - format_bbmapL200

  # Reference guidedworkflow
  targeted:
    stages:
      - qc
      - enrich
      - assemble_single
      - coverage
      - blastbin

  generic:
    stages:
      - qc
      - ref_hg38
      - deplete
      - assemble_meta
      - coverage
      - blastbin
      - scaffold
      - summarize

  rnaseq_salmon:
    stages:
      - qc
      - ref_hg38g
      - quant_salmon_sa
      - group_ALL
      - r_tximport

  rnaseq_star_rsem:
    stages:
      - qc
      - ref_hg38g
      - map_star
      - quant_rsem
      - group_ALL
      - r_tximport

  rnaseq_star_salmon:
    stages:
      - qc
      - ref_hg38g
      - map_star
      - quant_salmonG
      - group_ALL
      - r_tximport

