directories:
  rules:
    virprof:
      rules
conda:
  env_specs:
    - conda_envs

pipelines:
  ### Sub-Pipelines ###
  # Trimming and FastQC
  qc:
    stages:
      - qc_fastqc
      - trim_bbmapAQ10L70
      - qc_fastqc

  # Keep *only* reads matching last *.fasta.gz (from ref)
  enrich:
    stages:
      - map_bbmapS:
          hide: true
      - extract_readsG12

  # Remove reads matching last bowtie2 and hisat2 indicies (from ref)
  deplete:
    stages:
      - map_hisat2:
          hide: true
      - extract_readsf12:
          hide: true
      - map_bowtie2:
          hide: true
      - extract_readsf12

  # Assemble (by sample) using Spades Single Cell mode and remove short contigs
  assemble_single:
    stages:
      - group_sample
      - assemble_spadesSc:
          hide: true
      - format_bbmapL200

  # Assemble (by sample) using Spades Metagenomic mode and remove short contigs
  # (removes low entropy reads prior to assembly)
  assemble_meta:
    stages:
      - dust_bbmapE60:
          hide: true
      - group_sample
      - assemble_spadesMeta:
          hide: true
      - format_bbmapL200

  # Compute coverage and sorted bam file using bowtie2
  coverage:
    stages:
      - index_bowtie2:
          hide: true
      - map_bowtie2S:
          hide: true
      - sort_bam:
          hide: true
      - markdup_sambambaRM
      - coverage_samtools
      - basecov_bedtools

  # Remove human contigs and create classified bins using BLAST
  blastbin:
    stages:
      - ref_hg38:
          hide: true
      - annotate_blastE2MegaBest:
          hide: true
      - blastfilter_vpU200:
          hide: true
      - ref_NT:
          hide: true
      - annotate_blastE10Best:
          hide: true
      - ref_NcbiTaxonomy:
          hide: true
      - group_sample:
          hide: true
      - blastbin_vp

  scaffold:
    stages:
      - scaffold_vp
      - coverage:
          hide: true
      - group_sample
      - polish_pilon:
          hide: true
      - coverage
      - group_ALL
      - bin_vpSpecies

  summarize:
    stages:
      - ref_VHDB
      - group_ALL
      - summarize_vp

  # Re-Assemble created bins
  reassemble:
    stages:
      - enrich:
          hide: true
      - group_sample
      - group_BIN
      - assemble_spadesSc:
          hide: true
      - group_sample
      - format_bbmapL200

  # Reference guidedworkflow
  targeted:
    stages:
      - qc
      - enrich
      - assemble_single
      - coverage
      - blastbin

  generic:
    stages:
      - qc
      - ref_hg38
      - deplete
      - assemble_meta
      - coverage
      - blastbin
      - scaffold
      - summarize


# Configure local references
references:
  # Human reference used for read and contig filtering:
  hg38:
    # The index files for Bowtie2
    - url:
        databases/Homo_sapiens/UCSC/hg38/Sequence/Bowtie2Index/
      type: dirx
      files:
        ALL.1.bt2: genome.1.bt2
        ALL.2.bt2: genome.2.bt2
        ALL.3.bt2: genome.3.bt2
        ALL.4.bt2: genome.4.bt2
        ALL.rev.1.bt2: genome.rev.1.bt2
        ALL.rev.2.bt2: genome.rev.2.bt2
        ALL.fasta: genome.fa
    # The index files for Blast
    - url:
        databases/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/
      type: dirx
      files:
        ALL.nin: genome.fa.nin
        ALL.nhr: genome.fa.nhr
        ALL.nhi: genome.fa.nhi
        ALL.nhd: genome.fa.nhd
        ALL.nsq: genome.fa.nsq
        ALL.nsi: genome.fa.nsi
        ALL.nsd: genome.fa.nsd
        ALL.nog: genome.fa.nog
    # The index files for Hisat2
    - url:
        databases/grch38_snp_tran/
      type: dirx
      files:
        ALL.1.ht2: genome_snp_tran.1.ht2
        ALL.2.ht2: genome_snp_tran.2.ht2
        ALL.3.ht2: genome_snp_tran.3.ht2
        ALL.4.ht2: genome_snp_tran.4.ht2
        ALL.5.ht2: genome_snp_tran.5.ht2
        ALL.6.ht2: genome_snp_tran.6.ht2
        ALL.7.ht2: genome_snp_tran.7.ht2
        ALL.8.ht2: genome_snp_tran.8.ht2
  # NCBI Nucleotide database for Blast
  NT:
    - url:
        databases/nt/
      type: path
      match:
        - (?P<sample>[^.]+)\.((nal|not|nto|ntf|nos|ndb)|[0-9]+\.(nin|nhr|nsq|nsd|nog))
  # Subset of NT for testing
  NT_test:
    - url: test_data/nt_test.tar.bz2
      type: dir
      files: [nt.ndb, nt.nhr, nt.nin, nt.nog, nt.nos, nt.not, nt.nsq, nt.ntf, nt.nto]
      id: nt
  # NCBI Taxonomy dump for classification
  NcbiTaxonomy:
    - url:
        databases/NCBI_taxonomy/
      type: dirx
      files:
        ALL.NCBI.nodes.dmp: nodes.dmp
        ALL.NCBI.names.dmp: names.dmp
  # VirusHostDB from genome.jp
  VHDB:
    - url: ftp://ftp.genome.jp/pub/db/virushostdb/
      type: dirx
      files:
        virushostdb.tsv: virushostdb.tsv
  hrvc:
    - url: data/hrv_c_15.fasta.gz
  scov2:
    - url: data/sars_cov_2.fasta.gz
  hrvpb:
    - url: data/hrv_pb_unaligned.fasta.gz
